#!/usr/bin/env bash
#configure and install, update
balancer="\
frontend haproxy_balancer
    bind *:80
    mode http
    default_backend webservers
    
backend webservers
    balance roundrobin
    server 280506-web-01 52.3.243.233:80 check
    server 280506-web-02 18.204.20.81:80 check
"
#Update packages
apt-get -y update
apt-get -y upgrade

#AProxy PPA
apt-get -y install software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.5
apt-get -y update

#HAProxy
apt-get -y install haproxy
cp -a /etc/haproxy/haproxy.cfg{,.orig}
echo "$balancer" >> /etc/haproxy/haproxy.cfg
service haproxy restart
