#!/usr/bin/env bash
# print file name only after first dash
k=1
for (( ; k <= 100; k++))
do
	if (( k % 3 == 0 )) && (( k % 5 == 0 ))
	then
		echo "FizzBuzz"
	elif (( k % 3 == 0 ))
	then
		echo "Fizz"
	elif (( k % 5 == 0 ))
	then
		echo "Buzz"
	else
		echo $k
	fi
done
