#!/usr/bin/env bash
# tell stroty
while IFS=':' read -r username password uid gid info shell
do
	echo "The user $username is part of the $gid gang,"\
	"lives in $HOME and rides $shell."\
	"$uid's place is protected by the passcode $password,"\
	"more info about the user: $info"
done < "/etc/passwd"
