#!/usr/bin/env bash
# print bad and good luck in while
k=1
while ((k < 11))
do
	if ((k == 4))
	then
		echo "bad luck"
	elif ((k == 8))
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((k++))
done
