#!/usr/bin/env bash
# student file info
File=school
if [ -f "$File" ] || [ -e "$File" ]
then
	echo "school file exists"
	if [ -s school ]
	then
		echo "school file is not empty"
	else
		echo "school file is empty"
	fi
	if [ -f "$File" ]
	then
		echo "school is a regular file"
	fi
else
	echo "school file does not exist"
fi
