#!/usr/bin/env bash
#setting up ufw
sudo apt update
sudo apt-get install ufw
sudo ufw reset
sed -i 's/IPV6=.*/IPV6=yes/' /etc/default/ufw
sudo ufw enable
sudo ufw allow 22/tcp
sudo ufw allow 433/tcp
sudo ufw allow 80/tcp
sudo ufw disable
sudo ufw enable
