#!/usr/bin/env bash
#port forwarding by ufw
sudo sed -i 's/#net\/ipv4\/ip_forward=1/net\/ipv4\/ip_forward=1/' /etc/ufw/sysctl.conf
echo -e "*nat\n:PREROUTING ACCEPT [0:0]\n-A PREROUTING -p tcp --dport 8080 -j REDIRECT --to-port 80\nCOMMIT" | sudo tee -a /etc/ufw/before.rules
sudo ufw disable
sudo iptables --table nat --flush
sudo iptables --table nat --delete-chain
sudo ufw enable
