#!/usr/bin/env bash
#run nginx as nginx
sudo sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo sed -i 's/user .*;/user nginx;/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
sudo chown -R nginx:nginx /run/nginx.pid
sudo chown -R nginx:nginx /var/log/nginx/
sudo chown -R nginx:nginx /etc/nginx/
sudo nginx -t
sudo -u nginx service nginx start
