#!/usr/bin/env bash
#run nginx as nginx
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sed -i 's/user .*/user nginx/' /etc/nginx/nginx.conf
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
